import {
  Axe,
  Bath,
  Bolt,
  BrickWall,
  Boxes,
  Cable,
  Cog,
  Construction,
  Container,
  DoorOpen,
  Droplets,
  Drill,
  Fence,
  Flame,
  Gauge,
  Glasses,
  Hammer,
  HardHat,
  House,
  Key,
  Layers,
  Leaf,
  Lightbulb,
  Lock,
  Magnet,
  Nut,
  Package,
  PaintBucket,
  Paintbrush,
  Pipette,
  Plug,
  Ruler,
  Scissors,
  Shield,
  Shirt,
  ShowerHead,
  Shovel,
  Sprout,
  Thermometer,
  TreePine,
  Truck,
  Warehouse,
  Wind,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/** Icons an administrator can give a category (stored as the kebab-case key). */
export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  hammer: Hammer,
  wrench: Wrench,
  drill: Drill,
  'paint-bucket': PaintBucket,
  paintbrush: Paintbrush,
  zap: Zap,
  plug: Plug,
  lightbulb: Lightbulb,
  cable: Cable,
  droplets: Droplets,
  bath: Bath,
  'shower-head': ShowerHead,
  pipette: Pipette,
  'brick-wall': BrickWall,
  layers: Layers,
  boxes: Boxes,
  warehouse: Warehouse,
  'hard-hat': HardHat,
  ruler: Ruler,
  nut: Nut,
  bolt: Bolt,
  cog: Cog,
  house: House,
  fence: Fence,
  'tree-pine': TreePine,
  sprout: Sprout,
  shovel: Shovel,
  leaf: Leaf,
  shield: Shield,
  glasses: Glasses,
  shirt: Shirt,
  lock: Lock,
  key: Key,
  'door-open': DoorOpen,
  construction: Construction,
  container: Container,
  package: Package,
  truck: Truck,
  scissors: Scissors,
  axe: Axe,
  wind: Wind,
  flame: Flame,
  thermometer: Thermometer,
  magnet: Magnet,
  gauge: Gauge,
};

export const categoryIcon = (key: string | null | undefined): LucideIcon =>
  (key && CATEGORY_ICONS[key]) || Package;
